INSERT INTO instrument (instrument_type_id, brand, condition, lease_price, on_lease) VALUES
(1, 'Yamaha', 'Good condition, minor scratches on body', 250.00, FALSE),
(2, 'Stradivarius', 'Excellent condition, like new', 1500.00, FALSE),
(3, 'Moeck', 'Fair condition, some minor cracks', 90.00, FALSE),
(4, 'Bach', 'Good condition, slight dents', 200.00, FALSE),
(5, 'Pearl', 'Very good condition, no visible damage', 120.00, FALSE),
(6, 'Selmer', 'Brand new, no issues', 220.00, FALSE),
(7, 'Fender', 'Excellent condition, well-maintained', 130.00, FALSE),
(8, 'Giovanni', 'Fair condition, minor wear on body', 180.00, FALSE),
(9, 'Buffet Crampon', 'Good condition, well-kept', 110.00, FALSE),
(10, 'Hohner', 'Excellent condition, barely used', 140.00, FALSE),
(1, 'Kawai', 'Brand new, no signs of wear', 300.00, FALSE),
(2, 'Gibson', 'Good condition, light scuffs', 1700.00, FALSE),
(3, 'Gemeinhardt', 'Fair condition, some keypads need replacing', 95.00, FALSE),
(4, 'Jupiter', 'Very good condition, no dents', 210.00, FALSE),
(5, 'Tama', 'Good condition, some surface wear', 130.00, FALSE),
(6, 'Yamaha', 'Very good condition, like new', 230.00, FALSE),
(7, 'Ibanez', 'Good condition, slightly older model', 140.00, FALSE),
(8, 'Cremonese', 'Excellent condition, looks new', 190.00, FALSE),
(9, 'Yanagisawa', 'Good condition, some minor scratches', 125.00, FALSE),
(10, 'Sennheiser', 'Good condition, works perfectly', 150.00, FALSE),
(1, 'Roland', 'Fair condition, keys slightly worn', 270.00, FALSE),
(2, 'Czech', 'Excellent condition, well-maintained', 1600.00, FALSE),
(3, 'Yamaha', 'Fair condition, missing one key', 85.00, FALSE),
(4, 'Conn', 'Very good condition, no issues', 180.00, FALSE),
(5, 'DW', 'Good condition, minor scratches', 125.00, FALSE),
(6, 'Vandoren', 'Brand new, no signs of wear', 210.00, FALSE),
(7, 'Marshall', 'Good condition, minor scuffs', 150.00, FALSE),
(8, 'Boccherini', 'Fair condition, signs of age', 170.00, FALSE),
(9, 'Pearl', 'Very good condition, excellent tone', 130.00, FALSE),
(10, 'Scherzinger', 'Fair condition, slightly damaged', 160.00, FALSE),
(1, 'Yamaha', 'Good condition, minor scratches', 260.00, FALSE),
(2, 'Stradivarius', 'Excellent condition, almost new', 1550.00, FALSE),
(3, 'Moeck', 'Fair condition, slight cracks', 95.00, FALSE),
(4, 'Bach', 'Good condition, minor dents', 210.00, FALSE),
(5, 'Pearl', 'Very good condition, no visible damage', 125.00, FALSE),
(6, 'Selmer', 'Brand new, no issues', 230.00, FALSE),
(7, 'Fender', 'Excellent condition, well-maintained', 135.00, FALSE),
(8, 'Giovanni', 'Fair condition, some wear', 185.00, FALSE),
(9, 'Buffet Crampon', 'Good condition, well-kept', 115.00, FALSE),
(10, 'Hohner', 'Excellent condition, barely used', 145.00, FALSE),
(1, 'Kawai', 'Brand new, perfect condition', 310.00, FALSE),
(2, 'Gibson', 'Good condition, some light scratches', 1750.00, FALSE),
(3, 'Gemeinhardt', 'Fair condition, some keys need tuning', 100.00, FALSE),
(4, 'Jupiter', 'Very good condition, no damage', 215.00, FALSE),
(5, 'Tama', 'Good condition, minor surface wear', 135.00, FALSE),
(6, 'Yamaha', 'Very good condition, lightly used', 240.00, FALSE),
(7, 'Ibanez', 'Good condition, some wear on body', 145.00, FALSE),
(8, 'Cremonese', 'Excellent condition, no visible damage', 195.00, FALSE),
(9, 'Yanagisawa', 'Good condition, minor scratches', 130.00, FALSE),
(10, 'Sennheiser', 'Good condition, works well', 155.00, FALSE),
(1, 'Roland', 'Fair condition, some keys worn out', 280.00, FALSE),
(2, 'Czech', 'Excellent condition, maintained well', 1620.00, FALSE),
(3, 'Yamaha', 'Fair condition, missing a key', 90.00, FALSE),
(4, 'Conn', 'Very good condition, no visible defects', 190.00, FALSE),
(5, 'DW', 'Good condition, minimal scratches', 130.00, FALSE),
(6, 'Vandoren', 'Brand new, never used', 220.00, FALSE),
(7, 'Marshall', 'Good condition, minor wear', 155.00, FALSE),
(8, 'Boccherini', 'Fair condition, signs of aging', 175.00, FALSE),
(9, 'Pearl', 'Very good condition, great tone', 135.00, FALSE),
(10, 'Scherzinger', 'Fair condition, some minor damage', 165.00, FALSE);